#!/bin/bash
FILE=$1
MESSAGE=$(cat $FILE)
TICKET=$(git branch --show-current | grep  -Eo '^(\w+)-[0-9]+' | tr "[:lower:]" "[:upper:]")
if [[ $TICKET == "" || "$MESSAGE" == "$TICKET"* ]];then
  exit 0;
fi

echo "$TICKET | $MESSAGE" > $FILE
