#!/bin/bash
FILE=$1
TICKET=$(git branch --show-current | grep  -Eo '^(\w+)-[0-9]+' | tr "[:lower:]" "[:upper:]")

TMP_MESSAGE_FILE=$(mktemp)
trap "rm -f $TMP_MESSAGE_FILE" EXIT

while IFS='' read -r MESSAGE || [ -n "${MESSAGE}" ]; do
  if [ ! -z "$MESSAGE" ]; then
    if [[ $TICKET == "" || "$MESSAGE" == "$TICKET"* ]]; then
      echo "$MESSAGE" >> $TMP_MESSAGE_FILE
    else
      echo "$TICKET | $MESSAGE" >> $TMP_MESSAGE_FILE
    fi
  else
    echo "" >> $TMP_MESSAGE_FILE
  fi
done < $FILE

mv $TMP_MESSAGE_FILE $FILE
